### ISSUE TITLE
Improve visibility test

### ISSUE THREAD

**Issue by Metapyziks** [Metapyziks/FacePuncher#15]
Currently I'm just using a Bresenham line algorithm to trace a path from the observer to a tile, which isn't ideal as the visibility of a tile depends on exactly when the line changes row / column.

Ideally a tile would be visible if there exists a line that starts at the centre of the observer's tile and ends anywhere in the destination tile.

**Comment by Tamschi** [comment]
The current algorithm also isn't symmetric, for whatever reason. You can test this when walking around near the centre of a room with the old generator.

**Comment by Metapyziks** [comment]
Yep, it certainly needs replacing.

**Comment by Metapyziks** [comment]
Done, now uses a recursive shadow casting implementation.

283cda8a6a31090acb6f8f537c89f02b742b2cb2
