### ISSUE TITLE
Decide on extent of entity info sent to clients

### ISSUE THREAD

**Issue by Metapyziks** [Metapyziks/FacePuncher#2]
At the moment clients receive just the class name and IDs of any entities they can see, but from there we could go one of two ways.
- Send complete entity information during level state updates, allowing players to look at the properties of visible entities without additional requests
- Send only information about how to draw the entities, and require further requests when a player wishes to analyse an entity

The prior option would involve a lot more information being sent to clients during level visibility updates, but would then mean the player could freely analyse all visible entities without waiting for the server.

The latter would be perhaps cleaner to implement as we would then have a thin client, and communication between the client and the server would be minimised. However, the client may experience user interface delays while waiting for the server and a new server thread would currently be required to handle those requests.

**Comment by Tamschi** [comment]
I would say send things that can be determined by free actions (i.e. it looks like this, possibly what it's called, information that the player knows through previous actions like dissecting something). Everything else that has a time cost falls into the "never trust the client" rule and should only be revealed through the required actions.

I think user interface delays wouldn't be a very large issue: If the actions isn't free it's to be expected that it takes a moment to appear.

Rewriting the communication to allow fast unordered data requests isn't very difficult, I'll have a go at it later I think. You essentially just need request ids (set freely by the client) and awaitables (like the manually completed Tasks) that are fulfilled when the result comes in.

Something that would be very nice to have (if we are going for slow ticks/overall speed of actions) is telegraphing of intent. I think it's feasible to show small arrows when an entity or player decides to move for example. (As long as nothing important is in the way.)

**Comment by Metapyziks** [comment]
That all sounds fine to me, and feel free to modify the communication system into whatever you feel would work best. The implementation I have at the moment was more of a vertical slice to get something working and is in no way considered to be optimal.

**Comment by Tamschi** [comment]
I think I'll make the client a bit fatter so it signals intent instead of input. I'll also have to rewrite the protocol so the server never requests stuff... I think I probably could DoS the server with telnet right now :trollface:

**Comment by Metapyziks** [comment]
Shall we just move the Entity / Component classes to the server project from shared, and have the server send just structures that describe which symbols / colours to for each animation frame in the place of each entity?

I have in mind how I would implement it, but should I wait for your networking rewrite or would you be willing to incorporate it when you merge?

**Comment by Tamschi** [comment]
I think that's a good idea. I'll merge it into my branch before making a pull request.

**Comment by Metapyziks** [comment]
Alright, working on it now.

**Comment by Metapyziks** [comment]
Okay, it's ready.

**Comment by Tamschi** [comment]
Whoops, I merged your levelgen branch. Good job me :+1:

Works well though, I'll just wait until you're done with the levelgen to merge it back into master (if having the branches depend on each other is not an issue).

**Comment by Tamschi** [comment]
I looks like the conflicts are exactly the same and unaffected by the generation changes, so I'm remerging.

**Comment by Tamschi** [comment]
Fixed.

**Comment by Metapyziks** [comment]
I guess we've resolved this by choosing to send only display information, with the Entity and Component classes being entirely server-side.
