### ISSUE TITLE
There is too much documentation.

### ISSUE THREAD

**Issue by Tamschi** [Metapyziks/FacePuncher#7]
You don't have to repeat everything you do in a comment above if it's obvious. It's making the code _harder_ to read.

Really, most of it is readable enough as it is. You could probably delete 75% of the in-method comments and would end up with a much nicer version.
(Besides, ideally the code should speak for itself. The only case where that's definitely impossible is when you need to explain "why", not "what".)

(/rant)

**Comment by Metapyziks** [comment]
I'm so used to commenting coursework where we are expected to do that, but good point. Will save me a lot of time later too.

**Comment by Metapyziks** [comment]
Fixed. 921e6baa34f84dfeaef5c5005c068735af391e45 b15a6ae7945a8985edacbb7162951595509269fb 95cddfded26ce378a65c844c4899f8a6fabb6245 fb043d482845c2c5598d9d4d87d2b0e845c97777

**Comment by Tamschi** [comment]
Oh, good. Thanks!
I feared you had assimilated that bad habit for some reason.
